### ISSUE TITLE
1.2.1 Version Check

### ISSUE THREAD

**Issue by McGreggor** [PowerVCF/PowerVCF#107]
Hello, 
Firstly, thank-you for this module, great work ;)

Secondly there is problem with you CheckVCFVersion function when running on VCF 3.10.x.x as it come back with "This cmdlet is only supported in VCF 3.9 or later", and cmdlet doesn't complete.

**Comment by LifeOfBrianOC** [comment]
Hi McGreggor,

Release branch 1.2.1 hasnt been tested against 3.10.x so that function wasnt updated. You can update it by editing line 3451 of PowerVCF.psm1 and change 3.9 to 3.10 but YMMV!
