### ISSUE TITLE
Release 1.2.2 Set-VCFCredential header

### ISSUE THREAD

**Issue by McGreggor** [PowerVCF/PowerVCF#115]
Hi,

Spotted missing two lines to add in the privileged username/password to the API header in Set-VCFcredential function:
line: 1440
  $headers.Add("privileged-username", "$privilegedUsername")
  $headers.Add("privileged-password", "$privilegedPassword")

I did try to create a pull request to contribute this time but messed up somewhere :/

**Comment by McGreggor** [comment]
bump!

**Comment by LifeOfBrianOC** [comment]
Hey, Sorry this one was missed. I created release-1.2.3 branch and added the change. i dont have a 3.9 environment to test it so can you please test and let us know and i will mark it as the active branch for 3.x.

Thanks!

**Comment by McGreggor** [comment]
No worries, 1.2.3 tested in our environment and works great.  Thanks for the fix.

**Comment by GaryJBlake** [comment]
Issue fixed and included in 1.2.3 release https://www.powershellgallery.com/packages/PowerVCF/1.2.3
