### ISSUE TITLE
Generic global variables may cause incompatibilities with other modules

### ISSUE THREAD

**Issue by RockSlice** [PowerVCF/PowerVCF#118]
Suggest changing the following global variable names:

$global:accessToken -> $global:VCFaccesstoken
$global:refreshToken -> $global:VCFrefreshtoken
$global:base64AuthInfo -> $global:VCFbase64AuthInfo
$global:headers -> $global:VCFheaders
$global:ConfigJson -> $script:ConfigJson
$global:logFile > $script:logFile

As not all API calls are covered by PowerVCF yet, if the REST-related variables are made $script: variables, there should be a function available for custom API calls.

**Comment by GaryJBlake** [comment]
Acknowledging the feedback. Thank you @RockSlice time permitting we will look into this.
