### ISSUE TITLE
Token not returned with Request-VCFToken

### ISSUE THREAD

**Issue by jasemccarty** [PowerVCF/PowerVCF#120]
Attempting to connect to VCF 4.2.0.0 with Request-VCFToken

Cmdlet returns: 
**PS /Users/jase> Request-VCFToken -fqdn vcfvc01.fsa.lab -username powercli@vsphere.local -password XXXXX -basicAuth**
Successfully Requested New Basic Auth From SDDC Manager: vcfvc01.fsa.lab

When attempting to use Get-VCFHosts:
**PS /Users/jase> Get-VCFHost**
Write-Error: /usr/local/share/powershell/Modules/PowerVCF/2.1.2/PowerVCF.psm1:1985
Line  |
1985 |      checkVCFToken # Calls the CheckVCFToken function to validate the  …
         |      ~~~~~~~~~~~~~
         | API Access Token Required. Request an Access Token by running Request-VCFToken

Behavior is identical using PowerShell Core on Mac (7.1.3), PowerShell Core on Windows 10 (7.1.3), and PowerShell Desktop (5.1.19041.1023) on Windows 10. 

PowerVCF version is (2.1.2):
**PS /Users/jase> (Get-Module PowerVCF).Version**
Major  Minor  Build  Revision
-----  -----  -----  --------
2      1      2      -1

Versions in use are:
Software                                                Version                                           Build
SDDC Manager                                      4.2.0.0                                            17559673
VMware vCenter Server Appliance        7.0.1.00200                                    17327517
VMware ESXi                                         7.0.1                                               17551050
VMware NSX-T Data Center                 3.1.0.0.0                                          17107167
vRealize Suite Lifecycle Manager          8.2.0                                               17513665

**Comment by LifeOfBrianOC** [comment]
Hi Jase,

For 4.2 the basicAuth switch is not required for SDDC Manager connections as it uses token based auth. You should point the Request-VCFToken function at SDDC Manager using a user with the ADMIN role.

Brian

**Comment by jasemccarty** [comment]
Thanks Brian,
User has Administrator rights.
