### ISSUE TITLE
ESXi license value in json is wrong

### ISSUE THREAD

**Issue by m-gustafsson** [PowerVCF/PowerVCF#74]
As per the API guide, to specify a license for the ESXi hosts, the value should be "**licenseKey**", not "license". This is referenced in the WLD creation jsons.

https://vdc-download.vmware.com/vmwb-repository/dcr-public/906e5952-1237-4089-b618-a608b5efb1fc/47c2c76b-d71b-4fa0-bf17-57c292cd2395/index.html#_hostreference

**Comment by LifeOfBrianOC** [comment]
Resolved. Thanks Martin
