### ISSUE TITLE
VCF 3.7.2 on VxRail cannot connect to SDDC manager 

### ISSUE THREAD

**Issue by deepak-malhotra** [PowerVCF/PowerVCF#94]
Is there a minimum version of VCF supported by PowerVCF. Can't seem to connect to SSDC manager

PS C:\deepak\PowerVCF-master> Import-Module C:\deepak\PowerVCF-master\PowerVCF-master\PowerVCF.psd1
PS C:\deepak\PowerVCF-master> Connect-VCFManager -fqdn <xx> -username administrator@vsphere.local -password <xx>
PS C:\deepak\PowerVCF-master> Get-VCFHost

 API Access Token Required. Request an Access Token by running Connect-VCFManager

**Comment by LifeOfBrianOC** [comment]
PowerVCF does not support VCF 3.7.2. VCF 3.9 was the first fully supported version using release-1.1.0 branch

**Comment by deepak-malhotra** [comment]
> PowerVCF does not support VCF 3.7.2. VCF 3.9 was the first fully supported version using release-1.1.0 branch

Thanks for the quick reply @LifeOfBrianOC
